Resources:
  IlivalidatorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IlivalidatorLambdaRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::465066823493:policy/agi-s3
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "IlivalidatorLambdaFunctionLogPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: "logs:CreateLogGroup"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:eu-central-1:465066823493:log-group:/aws/lambda/ilivalidator:*"
      Roles: 
        - Ref: "IlivalidatorLambdaRole"
  IlivalidatorLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ilivalidator
      Role: !GetAtt IlivalidatorLambdaRole.Arn
      Runtime: java8.al2
      Handler: ch.so.agi.ilivalidator.IlivalidatorRequestHandler
      Code:
        S3Bucket: "ch.so.agi.ilivalidator"
        S3Key: "build/libs/ilivalidator-lambda-1.0.9999.jar"
      MemorySize: 2048
      Timeout: 900
      ReservedConcurrentExecutions: 25
      Environment:
        Variables:
          ILI_CACHE: /tmp
  version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref IlivalidatorLambdaFunction
      Description: v1
  aliasProd:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref IlivalidatorLambdaFunction
      FunctionVersion: !GetAtt version.Version
      Name: PROD
  aliasInt:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref IlivalidatorLambdaFunction
      FunctionVersion: !GetAtt version.Version
      Name: INT
  aliasTest:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref IlivalidatorLambdaFunction
      FunctionVersion: $LATEST
      Name: TEST
  LogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/ilivalidator"
      RetentionInDays: 7
